### ISSUE TITLE
Get automated test upload working

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/ProXamlToolbox#11]
```ascii
37s
Run EnricoMi/publish-unit-test-result-action/windows@v2
Run # Check for Python3
Check for Python3
Run actions/cache/restore@v4
Cache not found for input keys: enricomi-publish-action-Windows-X64-pip-3.9-b00485[1](https://github.com/mrlacey/ProXamlToolbox/actions/runs/11877723516/job/33097535117#step:8:1)9e3287ae9cfc634aeda40cbfe
Run # Create virtualenv
Create virtualenv
Run # Install Python dependencies
Install Python dependencies
Run # Publish Test Results
Publish Test Results
  2024-11-17 09:33:45 +0000 - publish -  INFO - Available memory to read files: 13.4 GiB
  2024-11-17 09:33:45 +0000 - publish -  INFO - Reading files testresults\**\*.trx (1 file, 17.9 KiB)
  2024-11-17 09:33:45 +0000 - publish -  INFO - Detected 1 TRX file (17.9 KiB)
  2024-11-17 09:33:45 +0000 - publish -  INFO - Finished reading 1 files in 0.02 seconds
  2024-11-17 09:33:45 +0000 - publish -  INFO - Publishing success results for commit 166b745a16b60c35c95d12afec6ddd65cb1c6e94
  Request POST /repos/mrlacey/ProXamlToolbox/check-runs failed with 403: Forbidden
  2024-11-17 09:33:46 +0000 - github.GithubRetry -  INFO - Request POST /repos/mrlacey/ProXamlToolbox/check-runs failed with 403: Forbidden
  Traceback (most recent call last):
    File "D:\a\_actions\EnricoMi\publish-unit-test-result-action\v2\python\publish_test_results.py", line 546, in <module>
      main(settings, gha)
    File "D:\a\_actions\EnricoMi\publish-unit-test-result-action\v2\python\publish_test_results.py", line 269, in main
      Publisher(settings, gh, gha).publish(stats, results.case_results, conclusion)
    File "D:\a\_actions\EnricoMi\publish-unit-test-result-action\v2\python\publish\publisher.py", line 233, in publish
      data = self.publish_check(data)
    File "D:\a\_actions\EnricoMi\publish-unit-test-result-action\v2\python\publish\publisher.py", line 461, in publish_check
      check_run = self._repo.create_check_run(name=self._settings.check_name,
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\github\Repository.py", line 3885, in create_check_run
      headers, data = self._requester.requestJsonAndCheck(
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 550, in requestJsonAndCheck
      return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line [71](https://github.com/mrlacey/ProXamlToolbox/actions/runs/11877723516/job/33097535117#step:8:73)5, in requestJson
      return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 812, in __requestEncode
      status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 846, in __requestRaw
      response = cnx.getresponse()
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\github\Requester.py", line 198, in getresponse
      r = verb(
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\requests\sessions.py", line 637, in post
      return self.request("POST", url, data=data, json=json, **kwargs)
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\requests\sessions.py", line 5[89](https://github.com/mrlacey/ProXamlToolbox/actions/runs/11877723516/job/33097535117#step:8:93), in request
      resp = self.send(prep, **send_kwargs)
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\requests\sessions.py", line 703, in send
      r = adapter.send(request, **kwargs)
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\requests\adapters.py", line 667, in send
      resp = conn.urlopen(
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\urllib3\connectionpool.py", line 934, in urlopen
      retries = retries.increment(method, url, response=response, _pool=self)
    File "D:\a\ProXamlToolbox\ProXamlToolbox\enricomi-publish-action-venv\lib\site-packages\github\GithubRetry.py", line 187, in increment
      raise Requester.createException(response.status, response.headers, content)  # type: ignore
  github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/checks/runs#create-a-check-run", "status": "403"}
Error: Process completed with exit code 1.
```

**Comment by mrlacey** [comment]
fixed it!
